%%% -*- Mode: Prolog; -*-


:- include('../domain/pickup_mdp.pl').

t1 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(mbot)) ~= bed,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
	observation(camera_tracker(coke)) ~= bed,
    observation(recognized(robert)) ~= true,
    observation(recognized(lynda)) ~= false,
    observation(recognized(melanie)) ~= false,
	observation(recognized(coke)) ~= true,
    observation(waiting_for_help) ~= none,
    observation(holding(coke)) ~= none],
    300,10,TotalR,T,10,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).

t2 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(mbot)) ~= bed,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
	observation(camera_tracker(coke)) ~= bed,
    observation(recognized(robert)) ~= true,
    observation(recognized(lynda)) ~= false,
    observation(recognized(melanie)) ~= false,
	observation(recognized(coke)) ~= true,
    observation(waiting_for_help) ~= none,
    observation(holding(coke)) ~= mbot],
    300,10,TotalR,T,10,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).

t3 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(mbot)) ~= bed,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
	observation(camera_tracker(coke)) ~= kitchen_table,
    observation(recognized(robert)) ~= true,
    observation(recognized(lynda)) ~= false,
    observation(recognized(melanie)) ~= false,
	observation(recognized(coke)) ~= false,
    observation(waiting_for_help) ~= none,
    observation(holding(coke)) ~= none],
    300,10,TotalR,T,10,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).

t4 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(mbot)) ~= kitchen_table,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
	observation(camera_tracker(coke)) ~= kitchen_table,
    observation(recognized(robert)) ~= false,
    observation(recognized(lynda)) ~= true,
    observation(recognized(melanie)) ~= false,
	observation(recognized(coke)) ~= true,
    observation(waiting_for_help) ~= none,
    observation(holding(coke)) ~= none],
    300,10,TotalR,T,10,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).

t5 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(mbot)) ~= kitchen_table,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
	observation(camera_tracker(coke)) ~= kitchen_table,
    observation(recognized(robert)) ~= false,
    observation(recognized(lynda)) ~= true,
    observation(recognized(melanie)) ~= false,
	observation(recognized(coke)) ~= true,
    observation(waiting_for_help) ~= (coke, lynda),
    observation(holding(coke)) ~= none],
    300,10,TotalR,T,10,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).

t6 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(mbot)) ~= bed,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= bed,
    observation(camera_tracker(melanie)) ~= sofa,
	observation(camera_tracker(coke)) ~= bed,
    observation(recognized(robert)) ~= false,
    observation(recognized(lynda)) ~= true,
    observation(recognized(melanie)) ~= false,
	observation(recognized(coke)) ~= true,
    observation(waiting_for_help) ~= (coke, lynda),
    observation(holding(coke)) ~= lynda],
    300,10,TotalR,T,10,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).

t7 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(mbot)) ~= kitchen_table,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
	observation(camera_tracker(coke)) ~= kitchen_table,
    observation(recognized(robert)) ~= false,
    observation(recognized(lynda)) ~= true,
    observation(recognized(melanie)) ~= false,
	observation(recognized(coke)) ~= true,
    observation(waiting_for_help) ~= none,
    observation(holding(coke)) ~= mbot],
    300,10,TotalR,T,10,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).

t8 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(mbot)) ~= bed,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
	observation(camera_tracker(coke)) ~= kitchen_table,
    observation(recognized(robert)) ~= true,
    observation(recognized(lynda)) ~= false,
    observation(recognized(melanie)) ~= false,
	observation(recognized(coke)) ~= true,
    observation(waiting_for_help) ~= none,
    observation(holding(coke)) ~= mbot],
    300,10,TotalR,T,10,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).

initdom1 :-
	init_particle(1000),
	step_particle([action(wait)],
    [observation(camera_tracker(coke)) ~= kitchen_table,
    observation(camera_tracker(mbot)) ~= kitchen_table,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
    observation(waiting_for_help) ~= none,
    observation(holding(coke)) ~= mbot,
    observation(recognized(robert)) ~= false,
    observation(recognized(lynda)) ~= false,
    observation(recognized(melanie)) ~= false,
    observation(recognized(coke)) ~= true],1000,1),
    log.

initdom2 :-
	init_particle(1000),
	step_particle([action(wait)],
    [observation(camera_tracker(coke)) ~= bed,
    observation(camera_tracker(mbot)) ~= bed,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
    observation(waiting_for_help) ~= none,
    observation(holding(coke)) ~= none,
    observation(recognized(coke)) ~= true,
    observation(recognized(robert)) ~= true,
    observation(recognized(lynda)) ~= false,
    observation(recognized(melanie)) ~= false],1000,1),
    log.

initdom3 :-
	init_particle(1000),
	step_particle([action(wait)],
    [observation(camera_tracker(coke)) ~= kitchen_table,
    observation(camera_tracker(mbot)) ~= kitchen_table,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
    observation(holding(coke)) ~= mbot,
    observation(waiting_for_help) ~= none,
    observation(recognized(coke)) ~= true,
    observation(recognized(robert)) ~= false,
    observation(recognized(lynda)) ~= false,
    observation(recognized(melanie)) ~= false],1000,1),
    log.

initdom4 :-
	init_particle(1000),
	step_particle([action(wait)],
    [observation(camera_tracker(coke)) ~= bed,
    observation(camera_tracker(mbot)) ~= kitchen_table,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
    observation(holding(coke)) ~= none,
    observation(waiting_for_help) ~= none,
    observation(recognized(coke)) ~= false,
    observation(recognized(robert)) ~= false,
    observation(recognized(lynda)) ~= true,
    observation(recognized(melanie)) ~= false],1000,1),
    log.

step_move(Place) :-
    write('[Executed Action]: navigate('), write(Place), writeln(')'),
    step_particle([action(navigate(Place))],O1,1000,1),
    log.

step_grasp :-
    write('[Executed Action]: grasp('), write('coke'), writeln(')'),
    step_particle([action(grasp(coke))],O1,1000,1),
    log.

step_wait :-
    writeln('[Executed Action]: wait'),
    step_particle([action(wait)],O1,1000,1),
    log.

step_deliver(Other) :-
    write('[Executed Action]: deliver(coke, '), write(Other), writeln(')'),
    step_particle([action(deliver(coke, Other))],O1,1000,1),
    log.

step_help(Other) :-
    write('[Executed Action]: ask_help(coke, '), write(Other), writeln(')'),
    step_particle([action(ask_help(coke, Other))],O1,1000,1),
    log.

step_recv(Other) :-
    write('[Executed Action]: receive(coke, '), write(Other), writeln(')'),
    step_particle([action(receive(coke, Other))],O1,1000,1),
    log.

log :-
    writeln(' ----------------------------------- '),
    eval_query_particle(current(located(mbot))~=bed, 1000, P1),
    eval_query_particle(current(located(mbot))~=kitchen_table, 1000, P2),
    eval_query_particle(current(located(mbot))~=sofa, 1000, P3),
    eval_query_particle(current(located(coke))~=bed, 1000, P4),
    eval_query_particle(current(located(coke))~=kitchen_table, 1000, P5),
    eval_query_particle(current(located(coke))~=sofa, 1000, P6),
    eval_query_particle(current(located(robert))~=bed, 1000, P7),
    eval_query_particle(current(located(robert))~=kitchen_table, 1000, P8),
    eval_query_particle(current(located(robert))~=sofa, 1000, P9),
    eval_query_particle(current(located(lynda))~=bed, 1000, P10),
    eval_query_particle(current(located(lynda))~=kitchen_table, 1000, P11),
    eval_query_particle(current(located(lynda))~=sofa, 1000, P12),
    eval_query_particle(current(located(melanie))~=bed, 1000, P13),
    eval_query_particle(current(located(melanie))~=kitchen_table, 1000, P14),
    eval_query_particle(current(located(melanie))~=sofa, 1000, P15),
    eval_query_particle(current(near(coke))~=true, 1000, P16),
    eval_query_particle(current(near(coke))~=false, 1000, P17),
    eval_query_particle(current(near(robert))~=true, 1000, P18),
    eval_query_particle(current(near(robert))~=false, 1000, P19),
    eval_query_particle(current(near(melanie))~=true, 1000, P20),
    eval_query_particle(current(near(melanie))~=false, 1000, P21),
    eval_query_particle(current(near(lynda))~=true, 1000, P22),
    eval_query_particle(current(near(lynda))~=false, 1000, P23),
    eval_query_particle(current(have(coke))~=mbot, 1000, P24),
    eval_query_particle(current(have(coke))~=robert, 1000, P25),
    eval_query_particle(current(have(coke))~=melanie, 1000, P26),
    eval_query_particle(current(have(coke))~=lynda, 1000, P27),
    eval_query_particle(current(have(coke))~=none, 1000, P28),
    eval_query_particle(current(asked)~=(none, none), 1000, P29),
    eval_query_particle(current(asked)~=(coke, robert), 1000, P30),
    eval_query_particle(current(asked)~=(coke, melanie), 1000, P31),
    eval_query_particle(current(asked)~=(coke, lynda), 1000, P32),
    write('mbot is in the: \t '), write('bed: '), write(P1),
    write('\t kitchen_table: '), write(P2), write('\t sofa: '), writeln(P3),
    write('coke is in the: \t '), write('bed: '), write(P4),
    write('\t kitchen_table: '), write(P5), write('\t sofa: '), writeln(P6),
    write('robert is in the: \t '), write('bed: '), write(P7),
    write('\t kitchen_table: '), write(P8), write('\t sofa: '), writeln(P9),
    write('lynda is in the: \t '), write('bed: '), write(P10),
    write('\t kitchen_table: '), write(P11), write('\t sofa: '), writeln(P12),
    write('melanie is in the: \t '), write('bed: '), write(P13),
    write('\t kitchen_table: '), write(P14), write('\t sofa: '), writeln(P15),
    write('mbot is near the coke: \t '), write('true: '), write(P16),
    write('\t false: '), writeln(P17),
    write('mbot is near robert: \t '), write('true: '), write(P18),
    write('\t false: '), writeln(P19),
    write('mbot is near melanie: \t '), write('true: '), write(P20),
    write('\t false: '), writeln(P21),
    write('mbot is near lynda: \t '), write('true: '), write(P22),
    write('\t false: '), writeln(P23),
    write('Who has the coke: \t'), write('mbot: '), write(P24),
    write('\t robert: '), write(P25), write('\t melanie: '), write(P26),
    write('\t lynda: '), write(P27), write('\t none: '), writeln(P28),
    write('Asked for help to get the coke to: \t'), write('nobody: '),
    write(P29), write('\t robert: '), write(P30),  write('\t melanie: '),
    write(P31), write('\t lynda: '), writeln(P32).

t1 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(coke)) ~= bed,
    observation(camera_tracker(mbot)) ~= bed,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
    observation(holding(coke)) ~= mbot,
    observation(waiting_for_help) ~= none,
    observation(recognized(coke)) ~= true,
    observation(recognized(robert)) ~= true,
    observation(recognized(lynda)) ~= false,
    observation(recognized(melanie)) ~= false],
    600,9,TotalR,T,9,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).

t2 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(coke)) ~= kitchen_table,
    observation(camera_tracker(mbot)) ~= kitchen_table,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
    observation(holding(coke)) ~= mbot,
    observation(waiting_for_help) ~= none,
    observation(recognized(coke)) ~= true,
    observation(recognized(robert)) ~= false,
    observation(recognized(lynda)) ~= true,
    observation(recognized(melanie)) ~= false],
    600,9,TotalR,T,9,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).

t3 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(coke)) ~= bed,
    observation(camera_tracker(mbot)) ~= bed,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
    observation(holding(coke)) ~= none,
    observation(waiting_for_help) ~= none,
    observation(recognized(coke)) ~= true,
    observation(recognized(robert)) ~= true,
    observation(recognized(lynda)) ~= false,
    observation(recognized(melanie)) ~= false],
    600,9,TotalR,T,9,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).

lab1 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(coke)) ~= bed,
    observation(camera_tracker(mbot)) ~= bed,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
    observation(holding(coke)) ~= none,
    observation(waiting_for_help) ~= none,
    observation(recognized(coke)) ~= true,
    observation(recognized(robert)) ~= true,
    observation(recognized(lynda)) ~= false,
    observation(recognized(melanie)) ~= false],
    200,9,TotalR,T,9,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).

lab2 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(coke)) ~= bed,
    observation(camera_tracker(mbot)) ~= bed,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
    observation(holding(coke)) ~= mbot,
    observation(waiting_for_help) ~= none,
    observation(recognized(coke)) ~= true,
    observation(recognized(robert)) ~= true,
    observation(recognized(lynda)) ~= false,
    observation(recognized(melanie)) ~= false],
    200,9,TotalR,T,9,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).

lab3 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(coke)) ~= bed,
    observation(camera_tracker(mbot)) ~= bed,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
    observation(holding(coke)) ~= robert,
    observation(waiting_for_help) ~= none,
    observation(recognized(coke)) ~= true,
    observation(recognized(robert)) ~= true,
    observation(recognized(lynda)) ~= false,
    observation(recognized(melanie)) ~= false],
    200,9,TotalR,T,9,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).

lab4 :-
    executedplan_start,
    executedplan_step(BA,false,
    [observation(camera_tracker(coke)) ~= kitchen_table,
    observation(camera_tracker(mbot)) ~= sofa,
    observation(camera_tracker(robert)) ~= bed,
    observation(camera_tracker(lynda)) ~= kitchen_table,
    observation(camera_tracker(melanie)) ~= sofa,
    observation(holding(coke)) ~= none,
    observation(waiting_for_help) ~= none,
    observation(recognized(coke)) ~= false,
    observation(recognized(robert)) ~= false,
    observation(recognized(lynda)) ~= false,
    observation(recognized(melanie)) ~= true],
    800,14,TotalR,T,14,STOP),
    write('Action chosen: '), writeln(BA),
    write('Timestep: '), writeln(T),
    write('Reward: '), writeln(TotalR).
